version: '3'

services:

  trainr:
    deploy:
      replicas: 1
    build: trainr
    environment:
      - PREDICTR_ENDPOINT=http://predictr:9999
    ports:
      - "7777:7777"
    volumes:
      - ./models:/app/models

  predictr:
    deploy:
      replicas: 1
    build: predictr
    ports:
      - "9999:9999"
    volumes:
      - ./models:/app/models