version: '3.5'

networks:
  bridge:
    driver: bridge

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    expose:
      - "2181"
    ports:
      - "2181:2181"
    networks:
      bridge:
        aliases:
          - zookeeper
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    expose:
      - "9092"
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka  #127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    networks:
      bridge:
        aliases:
          - kafka

  producer:
    container_name: producer
    build: ./kafka-producer
    restart: always
    depends_on:
     - zookeeper
     - kafka
    networks:
      bridge:
        aliases:
          - kafka-producer
  
  consumer:
    container_name: consumer
    build: ./Kafka-Consumer
    restart: always
    depends_on:
     - zookeeper
     - kafka
     - producer
    networks:
      bridge:
        aliases:
          - kafka-consumer